# Generated by Django 4.1.1 on 2022-09-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo_empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_lab', models.IntegerField()),
                ('mes_lab', models.IntegerField()),
                ('empresa', models.CharField(max_length=100)),
                ('jefe_inmediato', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('responsabilidades', models.CharField(max_length=500)),
                ('logros', models.CharField(max_length=500)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo_empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_est', models.IntegerField()),
                ('mes_est', models.IntegerField()),
                ('estudio', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo_empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('numero_documento', models.IntegerField(default=0)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(default=0)),
                ('tipo_sangre', models.CharField(max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo_empleados.empleado')),
            ],
        ),
    ]
