# Generated by Django 4.1.1 on 2022-09-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dato',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
